### Create a new Post:
POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Basic admin admin

{
  "title": "Bcc Dpring Data Validations 332",
  "description": "Validation Annatations for spring",
  "content": "@UniqueTitle Annatation prevents null values - @Valid"
}


### Create another Post:
POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Basic admin admin

{
  "title": "Bfff Dpring Data Validations 332",
  "description": "Validation Annatations for spring",
  "content": "@UniqueTitle Annatation prevents null values - @Valid"
}


### Create new Post2:
POST http://localhost:8080/api/v1/posts
Content-Type: application/json
Authorization: Basic admin admin

{
  "title": "Spring security",
  "description": "Password encoding",
  "content": "Password encoding"
}



### Get all posts:
GET http://localhost:8080/api/v1/posts
Authorization: Basic mike Password1!


### Get a valid posts by id:
GET http://localhost:8080/api/v1/posts/1
Authorization: Basic mike Password1!



### Get an invalid posts by id:
GET http://localhost:8080/api/v1/posts/1111
Authorization: Basic mike Password1!


### Update a post:
PUT http://localhost:8080/api/v1/posts/1
Authorization: Basic admin admin
Content-Type: application/json

{
  "title": "A  otNull Annatation prevents null values - @Valid!!!",
  "description": "Validation Annatations for spring!",
  "content": "Spring Data Validations!!!"
}


### Delete a Post By ID:
DELETE http://localhost:8080/api/v1/posts/3
Authorization: Basic mike Password1!


### Get posts by page 1:
GET http://localhost:8080/api/v1/posts/page?pageSize=2&pageNo=0
Authorization: Basic mike Password1!

### Get posts  page 2:
GET http://localhost:8080/api/v1/posts/page?pageSize=2&pageNo=1
Authorization: Basic mike Password1!


### Get posts  page with sort and sort order:
GET http://localhost:8080/api/v1/posts/page?pageSize=6&pageNo=0&sortBy=id&sortDir=asc
Authorization: Basic mike Password1!
